//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PCSW.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_PCSW_FORM                   101
#define IDD_PROPPAGE_CONTACT            106
#define IDD_PROPPAGE_VIEW               107
#define IDR_MAINFRAME                   128
#define IDR_PCSWTYPE                    129
#define IDC_CURSOR1                     130
#define IDP_OLE_INIT_FAILED             130
#define IDB_BITMAP1                     131
#define IDD_DIALOG_COMSET               132
#define IDD_SETTING_FORM                133
#define IDD_MENU_FORM                   134
#define IDD_ZONE_FORM                   136
#define IDR_CTC50                       137
#define IDR_DCS                         138
#define IDD_SCAN_FORM                   139
#define IDD_DPMR_FORM                   141
#define IDD_PROPPAGE_GROUPLIST          142
#define IDD_PROPPAGE_SMS                143
#define IDD_MENUKEY_FORM                144
#define IDD_GRID_VIEW                   145
#define IDC_COMBO_COMSET                1000
#define IDC_EDIT_SERIALNUM              1001
#define IDC_EDIT_MACHINE_TYPE           1002
#define IDC_EDIT_FREQ_RANGE             1003
#define IDC_CHECK_TALKAROUND            1003
#define IDC_EDIT_SW_VERSION             1004
#define IDC_CHECK_LANGUAGE              1004
#define IDC_EDIT_DATA_VERSION           1005
#define IDC_CHECK_VOX                   1005
#define IDC_CHECK_BRIGHT                1006
#define IDC_EDIT_VISION_VERSION         1006
#define IDC_CHECK_WHISPER               1007
#define IDC_COMBO_FREQ_RANGE            1007
#define IDC_CHECK_BGLIGHT               1008
#define IDC_CHECK_LOWPOWER_TONE         1008
#define IDC_CHECK_TONE                  1009
#define IDC_CHECK_KEY_TONE              1009
#define IDC_CHECK_POWERLVL              1010
#define IDC_CHECK_SMS_TONE              1010
#define IDC_CHECK_NOISELVL              1011
#define IDC_CHECK_CH_LOCK               1011
#define IDC_CHECK_KEYPADLOCK            1012
#define IDC_CHECK_WHISPER_EN            1012
#define IDC_CHECK_POWERSAVE             1013
#define IDC_CHECK_KEYLOCK               1013
#define IDC_CHECK_MAINFRAME             1014
#define IDC_CHECK_VOX_CANCEL            1014
#define IDC_CHECK_SCAN                  1015
#define IDC_CHECK_VOX_FORBID            1015
#define IDC_CHECK_SCANCHECK             1016
#define IDC_CHECK_LIGHT_NOTE            1016
#define IDC_CHECK_SCAN_TEMP_DELE        1017
#define IDC_CHECK_VIBRATE_NOTE          1017
#define IDC_CHECK_SCAN_TEMP_ADD         1018
#define IDC_CHECK_DATE_SHOW             1018
#define IDC_CHECK_SCAN_ADD_CH           1019
#define IDC_CHECK_WILDCARD              1019
#define IDC_CHECK_SCAN_DELE_CH          1020
#define IDC_CHECK_MANUAL_DIAL           1020
#define IDC_CHECK_WRITE_SMS             1021
#define IDC_CHECK_ALLOW_CALLALL         1021
#define IDC_CHECK_SMS                   1022
#define IDC_CHECK_ALLOW_GROUPCALL       1022
#define IDC_CHECK_ADD_CONTACT           1023
#define IDC_CHECK_ALLOW_ADD_CONTACT     1023
#define IDC_CHECK_CONTACT_DELE          1024
#define IDC_CHECK_ALLOW_WRITE_SMS       1024
#define IDC_CHECK_ALLOW_UNKILL          1025
#define IDC_CHECK_DECODE_KILL           1025
#define IDC_CHECK_ALLOW_KILL            1026
#define IDC_CHECK_POWERSAVELVL          1026
#define IDC_CHECK_DECODE_KILLANDACTIVE  1027
#define IDC_COMBO_VOX_LVL               1027
#define IDC_CHECK_LED_LIGHT_MENU        1028
#define IDC_COMBO_BGLIGHT               1028
#define IDC_CHECK_VIBRATE_MENU          1029
#define IDC_COMBO_NOISE_LVL             1029
#define IDC_CHECK_DATE_MENU             1030
#define IDC_COMBO_TONE                  1030
#define IDC_CHECK_ENHANCE_SPEECH_MENU   1031
#define IDC_COMBO_IN_TONE               1031
#define IDC_CHECK_VOICE_ENCRYPT_MENU    1032
#define IDC_COMBO_OUT_TONE              1032
#define IDC_COMBO_POWER_LVL             1033
#define IDC_EDIT_ID                     1034
#define IDC_SPIN_PRE_TX_DELAY           1035
#define IDC_COMBO_MAINFRAME_STYLE       1036
#define IDC_EDIT_PRE_TX_DELAY           1037
#define IDC_GRID_ZONEINFO               1037
#define IDC_EDIT_GROUPCALL_HOLD_TIME    1038
#define IDC_EDIT_ZONE                   1038
#define IDC_SPIN_GROUPCALL_HOLD_TIME    1039
#define IDC_COMBO_ZONE                  1039
#define IDC_EDIT_SIGNALCALL_HOLD_TIME   1040
#define IDC_STATIC_ZONENUM              1040
#define IDC_SPIN_SIGNALCALL_HOLD_TIME   1041
#define IDC_BUTTON_NEXT                 1041
#define IDC_EDIT_VOX_DELAY              1042
#define IDC_BUTTON_LAST                 1042
#define IDC_SPIN_VOX_DELAY              1043
#define IDC_BUTTON_FIRST                1043
#define IDC_EDIT_BGLIGHT_DELAY          1044
#define IDC_BUTTON_PREV                 1044
#define IDC_SPIN_BGLIGHT_DELAY          1045
#define IDC_BUTTON_ADD                  1045
#define IDC_EDIT_KEYLOCK_DELAY          1046
#define IDC_BUTTON_INSERT               1046
#define IDC_BUTTON_ADD_SCANLIST         1046
#define IDC_BUTTON_DEL                  1046
#define IDC_SPIN_KEYLOCK_DELAY          1047
#define IDC_BUTTON_DELETE               1047
#define IDC_EDIT_ALARM_NAME             1048
#define IDC_COMBO_ZONELIST              1048
#define IDC_BUTTON_INSERT2              1048
#define IDC_COMBO_ALARM_TYPE            1049
#define IDC_GRID_ZONE                   1049
#define IDC_BUTTON_DELETE_SCANLIST      1049
#define IDC_COMBO_ALARM_MODE            1050
#define IDC_LIST_AVAIBLE_CHANNEL        1050
#define IDC_COMBO_ALARM_CHANNEL         1051
#define IDC_LIST_USED_CHANNEL           1051
#define IDC_EDIT_ALARM_CALL_TIME        1052
#define IDC_SPIN_ALARM_CALL_TIME        1053
#define IDC_EDIT_SCANLIST_NAME          1053
#define IDC_EDIT_ALAMR_TIME             1054
#define IDC_COMBO_SCANMODE              1054
#define IDC_SPIN_ALARM_TIME             1055
#define IDC_COMBO_SCAN_ON_TIME          1055
#define IDC_EDIT_MIC_HOLD_TIME          1056
#define IDC_COMBO_SCAN_TXMODE           1056
#define IDC_SPIN_MIC_HOLD_TIME          1057
#define IDC_COMBO_SCAN_TXCHANNEL        1057
#define IDC_EDIT_RCV_HOLE_TIME          1058
#define IDC_COMBO_SCAN_RCVDELAY         1058
#define IDC_SPIN_RCV_HOLD_TIME          1059
#define IDC_COMBO_SCAN_SENDDELAY        1059
#define IDC_EDIT_TCOMM                  1060
#define IDC_RADIO_CALLBACK              1060
#define IDC_SPIN_TCOMM                  1061
#define IDC_STATIC_SCANLIST             1061
#define IDC_EDIT_TPRETOT                1062
#define IDC_EDIT_ZONENAME               1062
#define IDC_COMBO_SCAN_CALLBACK         1062
#define IDC_SPIN_TPRETOT                1063
#define IDC_EDIT_TREKEY                 1064
#define IDC_GRID_CONTACT                1064
#define IDC_GRID_CONTACT_1              1064
#define IDC_SPIN_TREKEY                 1065
#define IDC_GRID_SMS                    1065
#define IDC_GRID_CONTACT_2              1065
#define IDC_EDIT_TRESET                 1066
#define IDC_EDIT_SMS                    1066
#define IDC_SPIN_TRESET                 1067
#define IDC_STATIC_SHEET                1067
#define IDC_EDIT_CONTENT                1068
#define IDC_EDIT_ALARM_EMEID            1069
#define IDC_COMBO_TYPE                  1069
#define IDC_LIST_ALL_MEMBER             1070
#define IDC_LIST_USED_MEMBER            1071
#define IDC_EDIT_NAME                   1072
#define IDC_LIST_MENU                   1077
#define IDC_STATIC_KEYNAME_1            1082
#define IDC_STATIC_KEYNAME_2            1083
#define IDC_STATIC_KEYNAME_3            1084
#define IDC_STATIC_KEYNAME_4            1085
#define IDC_STATIC_KEYNAME_5            1086
#define IDC_STATIC_KEYNAME_6            1087
#define IDC_STATIC_KEYNAME_7            1088
#define IDC_STATIC_KEYNAME_8            1089
#define IDC_STATIC_KEYNAME_9            1090
#define IDC_STATIC_KEYNAME_10           1091
#define IDC_STATIC_KEYNAME_11           1092
#define IDC_COMBO_KEYFUNC_1             1093
#define IDC_COMBO_KEYFUNC_2             1094
#define IDC_COMBO_TOT_1                 1094
#define IDC_COMBO_KEYFUNC_3             1095
#define IDC_COMBO_TOT_2                 1095
#define IDC_COMBO_KEYFUNC_4             1096
#define IDC_COMBO_TOT_3                 1096
#define IDC_CUSTOM2                     1096
#define IDC_COMBO_KEYFUNC_5             1097
#define IDC_COMBO_TOT_4                 1097
#define IDC_CUSTOM1                     1097
#define IDC_COMBO_KEYFUNC_6             1098
#define IDC_COMBO_EMER_1                1098
#define IDC_BUTTON_CONT_ADD             1098
#define IDC_COMBO_KEYFUNC_7             1099
#define IDC_COMBO_EMER_2                1099
#define IDC_BUTTON_CONT_DEL             1099
#define IDC_BUTTON_DELETE_GRPLIST       1099
#define IDC_COMBO_KEYFUNC_8             1100
#define IDC_COMBO_EMER_3                1100
#define IDC_BUTTON_ADD_GRPLIST          1100
#define IDC_COMBO_KEYFUNC_9             1101
#define IDC_COMBO_TOT_8                 1101
#define IDC_COMBO_EMER_4                1101
#define IDC_STATIC_GRP                  1101
#define IDC_COMBO_KEYFUNC_10            1102
#define IDC_COMBO_KEYFUNC_11            1103
#define ID_WRITE_PARAMETER              32771
#define ID_READ_PARAMETER               32772
#define ID_COPY_PARAMETER               32773
#define ID_RESET                        32774
#define ID_BUTTON32775                  32775
#define ID_COMM_SET                     32776

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        146
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         1103
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
